### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by cupnoodles14** [wsdfhjxc/virtual-desktop-bar#12]
Hello! I've added your applet to AUR, hope you don't mind (I should've probably asked you about the name and everything).

https://aur.archlinux.org/packages/plasma-virtual-desktop-bar-git/

Actually, I think I should've named it "plasma5-applets-virtual-desktop-bar-git" instead. I'll wait a couple of days before submitting a rename request in case you want to change it to something else (or remove it etc).

**Comment by wsdfhjxc** [comment]
That's actually pretty cool. I'm perfectly fine with that. Thank you very much!

**Comment by cupnoodles14** [comment]
Great! I have submitted a rename request. You can add this AUR link/package name to the readme if you want to. 
https://aur.archlinux.org/packages/plasma5-applets-virtual-desktop-bar-git/
