### ISSUE TITLE
2-3 second lag to show the current desktop after switching

### ISSUE THREAD

**Issue by ripefig** [wsdfhjxc/virtual-desktop-bar#17]
1. Switch desktop.
2. Desktop bar still indicates you're on the old desktop.
3. Wait at least two seconds.
4. Desktop bar is updated to reflect desktop change.

So basically, the widget fails to provide proper visual feedback when switching desktops. If you switch through desktops rapidly, you get no visual feedback at all.

Any way this lag could be reduced?

**Comment by wsdfhjxc** [comment]
I have no idea, as it works instantly for me, without any kind of a lag. Can you tell me what distro are you using, as well as Plasma and Qt versions? Maybe I could somehow reproduce the issue.

**Comment by ripefig** [comment]
I figured it out. The lag is due to latte dock - it doesn't happen with the regular plasma panel. So it's very unlikely you can fix the bug on your end. A bug could be filed with latte dock.

**Comment by wsdfhjxc** [comment]
I'm using Latte (0.9.2) instead of the default Plasma panel, and it works fine.

Anyway, I'm sorry that I can't help you, but I don't know how to reproduce the issue.

**Comment by ripefig** [comment]
I am on 0.9.85
You'll probably encounter it you upgrade to the git version.

**Comment by wsdfhjxc** [comment]
I did a clean install of Latte version 0.9.85, imported my layout with the widget, and it still works correctly. The indicator and label changes are instant for me. No idea what might be wrong.

**Comment by ripefig** [comment]
It works after reboot. Not sure what the cause of the cause of the slowdown was, but it was some porary latter glitch.
