### ISSUE TITLE
Request: Vertical Layout for Buttons

### ISSUE THREAD

**Issue by AndydeCleyre** [wsdfhjxc/virtual-desktop-bar#20]
Arch Linux
Plasma `5.17.0`
VDB `r379.b3fa1f8`

The always-horizontal layout of buttons doesn't make optimal use of space when placed on a wide vertical panel:

![image](https://user-images.githubusercontent.com/1787385/67043966-39dfc500-f0f9-11e9-872b-e7be8e6b61ed.png)

It would be nice, in this context, to have a column of thin horizontal buttons spanning the available width.

**Comment by wsdfhjxc** [comment]
Implemented in version 0.7.0.
