### ISSUE TITLE
Error loading QML file

### ISSUE THREAD

**Issue by jankolf** [wsdfhjxc/virtual-desktop-bar#21]
Hi,
I followed the install instructions (also installed all dependencies) but after adding the widget to my panel I get the following error:
`Error loading QML file: file:///usr/share/plasma/plasmoids/org.kde.plasma.virtualdesktopbar/contents/ui/Applet.qml:4:1: module "org.kde.plasma.virtualdesktopbar" is not installed`

I am running Kubuntu 19.10 with KDE 5.62.0 / Plasma 5.16.5.

**Comment by wsdfhjxc** [comment]
I've set up a fresh Kubuntu 19.10 VM with the same Plasma and KDE Frameworks versions, and I can't reproduce the issue. However, that error can occur when a plasmoid's library file is installed in a wrong location. Can you tell me if the `libvirtualdesktopbarplugin.so` file exists in `/usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/plasma/virtualdesktopbar` directory?
