### ISSUE TITLE
[Request] Display icons instead of text/numbers

### ISSUE THREAD

**Issue by pcapiod** [wsdfhjxc/virtual-desktop-bar#24]
Hi,
Thanks for this really nice widget, love it !

I would like to know, would it be possible to display an icon to symbolize the desktop instead of text or numbers ? Like display an icon of a terminal for terminal desktop, a folder for the filer manager desktop, mais for emails etc, similar to what it's possible on i3/AwesomeWM/... ?

Thanks again !

**Comment by wsdfhjxc** [comment]
It's already possible. Install FontAwesome on your system and set it as a custom font in the Appearance section of the applet's configuration dialog. Then you just need to find icons, copy their Unicode glyphs, and simply rename each of your desktops and use the copied character as it's name.

You can use KCharSelect application to discover available Unicode glyphs provided by FontAwesome. Choose the FontAwesome font, then select "Other" and "Private Use Area" in the drop-down lists. Then you'll see a grid of icons, which you can copy to the clipboard. I hope that helps.

**Comment by pcapiod** [comment]
Hi,
Awesome, perfect ! Thanks for your answer :)
