### ISSUE TITLE
Feature request: sort desktops labels by name

### ISSUE THREAD

**Issue by Avi-D-coder** [wsdfhjxc/virtual-desktop-bar#28]
I use this with i3 by only displaying desktop name, I would like an option to order the widget by name. This would prevent the i3 desktop named `"2"` numbered `1` from being displayed first.
**name**
![image](https://user-images.githubusercontent.com/29133776/80748920-b06f6d80-8af3-11ea-9669-252ec7eb9adb.png)

**number : name**
![image](https://user-images.githubusercontent.com/29133776/80749370-53c08280-8af4-11ea-9fb2-36deda28bd68.png)

Thanks for the great plugin!

**Comment by wsdfhjxc** [comment]
I'm sorry but I have to pass. For i3-specific support, I suggest to take a look at this applet: https://github.com/duvholt/i3-pager
