### ISSUE TITLE
[Feature Request] Show only desktops with Windows 

### ISSUE THREAD

**Issue by pranavtifr** [wsdfhjxc/virtual-desktop-bar#31]
Similar to the option of show only current desktop. I would be great if there is an option of showing only desktops which have an open window. 

Example:
![image](https://user-images.githubusercontent.com/30164619/85222174-bf2d1f00-b3d6-11ea-82a7-74876915c2a0.png)
In this image, It would be great if there is an option to show only Konsole (Since it is the current desktop) and Firefox (Since it is the desktop with an open window)

Thanks a lot for this plugin. It is wonderful.

**Comment by master-of-zen** [comment]
+1 on this

**Comment by wsdfhjxc** [comment]
This will be available in version 1.0.
