### ISSUE TITLE
[Feature Request] - Keyboard shortcut to rename current desktop

### ISSUE THREAD

**Issue by victorbrca** [wsdfhjxc/virtual-desktop-bar#34]
Congrats on the amazing work. This pager is great and is something that was missing for plasma. 

It would be nice to have a keyboard shortcut to rename the current desktop. My workflow is that I have one desktop for each task, and I rename the desktop as soon as it's created. Having a keyboard shortcut would be great.

**Comment by victorbrca** [comment]
Never mind. This can be done with Kwin.

![](https://i.imgur.com/o1fUtsk.png)

**Comment by wsdfhjxc** [comment]
This is actually a non-standard shortcut provided by Virtual Desktop Bar, and [here](https://github.com/wsdfhjxc/virtual-desktop-bar#configuration) is a list of such shortcuts.
