### ISSUE TITLE
[Feature Request] - Right click move desktop to the end

### ISSUE THREAD

**Issue by victorbrca** [wsdfhjxc/virtual-desktop-bar#35]
If you have the 3 options enabled:

+ `Always keep at least one empty desktop`
+ `Automatically remove redundant empty desktops`
+ `Automatically rename empty desktops as: Empty`

When you close all windows on that desktop, the last `Empty` desktop is removed and you get an `Empty` desktop in the middle of all desktops. It would be nice to be able to right-click the desktop and have an option to `Move current desktop to end`. 

Cheers!

**Comment by wsdfhjxc** [comment]
Dragging desktops with the mouse will be available in version 1.0. That should cover this use case.
