### ISSUE TITLE
[Feature Request] Option to remove 'plus' button

### ISSUE THREAD

**Issue by gariti** [wsdfhjxc/virtual-desktop-bar#37]
I would like to have the option to remove the '+' button since I keep accidentally clicking on it and create new desktops I don't need.  Thank you for creating this applet!

**Comment by wsdfhjxc** [comment]
That option already exists. You can find it at the bottom of the Appearance tab in the configuration dialog.

**Comment by gariti** [comment]
Awesome, thanks! I just didn't see you could scroll down for more options :Z
