### ISSUE TITLE
Does not work with BSPWM Workspaces

### ISSUE THREAD

**Issue by 5310** [wsdfhjxc/virtual-desktop-bar#41]
This widget cannot show BSPWM Workspaces; simply shows a blank widget (and the plus icon if it's enabled). While BSPWM is active the "stock" KDE pager widget can still list the BSPWM Workspaces.

Example screenshot on Kubuntu 20.04.1 with Virtual Desktop Bar as the second widget from the left (blank space with plus icon) and then the stock pager: 

![Screenshot_2020-10-31_11-14-42](https://user-images.githubusercontent.com/112914/97772561-63398a80-1b6e-11eb-8ee7-78803899ee11.png)

**Comment by wsdfhjxc** [comment]
Thanks for reporting. I'll try to make it work again with other window managers.

**Comment by 5310** [comment]
Thank you very much. I read that it works with i3 so I was afraid I was
doing something wrong with BSPWM, but even failed in a live install, so...
I'll wait for any updates :D

**Comment by wsdfhjxc** [comment]
Actually, your issue made me realize that, after the changes in the 1.0 version, the plasmoid doesn't work with any other window manager than KWin. It's just my stupidity that is in fault. I'll provide some fallback code paths, so it will work without KWin.

**Comment by wsdfhjxc** [comment]
All right, it should be working now. Please check out the master branch and let me know if it is.

**Comment by 5310** [comment]
It works perfectly now! :raised_hands: 

I just ran the uninstall script, pulled, installed again and it worked after the re-log! Ofc the plus button doesn't work, but that's entirely to be expected (and I at least don't need it anyway:)

Thanks a lot for such a quick fix. Sorry to have ate up your Halloween with a bug, but I appreciate it a lot  :]
