### ISSUE TITLE
Option to always show current desktop when "Show button only for occupied desktop" is enabled

### ISSUE THREAD

**Issue by EllBock** [wsdfhjxc/virtual-desktop-bar#42]
Hi, as the title says, I was wondering if it was possible to add an option that makes the current selected desktop visible in the applet even if it is not occupied when "Show button only for occupied desktop" is enabled.

For example, I have 9 fixed desktops and the option enabled. If desktops 1 to 4 are occupied, and I am on desktop 5 which is empty, I would like to see desktop 1 to 4, but also desktop 5 highlighted, which is not the case right now.

I like the fact that the applet can hide non occupied desktops, but if I am on an empty one the applet doesn't show which desktop I'm currently on, and this information is missed when switching frequently. 

Thank you for this great alternative to the default desktop switcher :)

**Comment by wsdfhjxc** [comment]
I'll take a look at this.

**Comment by wsdfhjxc** [comment]
This will be fixed in version 1.3. If you want it right now, please check out the `testing` branch.
