### ISSUE TITLE
Spacing beetween desktops with only show occupied and active desktops

### ISSUE THREAD

**Issue by master-of-zen** [wsdfhjxc/virtual-desktop-bar#45]
Original desktops
![2020_11_27_14_28_56](https://user-images.githubusercontent.com/46526140/100449635-ef32c980-30bc-11eb-8fec-3f29c6dc8e85.png)

desktop #1 and #2 just fine
![2020_11_27_14_25_03](https://user-images.githubusercontent.com/46526140/100449771-2bfec080-30bd-11eb-8fc9-7e9907134927.png)
same with #1 #2 #3 
![2020_11_27_14_25_06](https://user-images.githubusercontent.com/46526140/100449813-3ae57300-30bd-11eb-9690-7edc10d58d51.png)

When I go to desktop #9, it have big space between them, and this space is clickable - meaning I can click on that space and go to 'hidden' desktops
![2020_11_27_14_25_10](https://user-images.githubusercontent.com/46526140/100450017-94e63880-30bd-11eb-92bf-3f62d671967e.png)

<details>
  <summary>Here is my appearance settings</summary>
 
![2020_11_27_14_34_47](https://user-images.githubusercontent.com/46526140/100450547-864c5100-30be-11eb-8f3e-632feeacedf3.png)

</details>

:slightly_smiling_face: Please fix

**Comment by master-of-zen** [comment]
Also if I scroll desktops the all mash together
![2020_11_27_14_42_41](https://user-images.githubusercontent.com/46526140/100450767-e511ca80-30be-11eb-8dcc-78b110fd59fa.png)

**Comment by wsdfhjxc** [comment]
I can't reproduce this issue.

In case this is Latte Dock, please open Konsole and run the following:

```
TMP_FILE="/tmp/lattedock-debug.txt"
FILE="$HOME/virtualdesktopbar-debug.txt"
latte-dock --debug --replace > "$TMP_FILE" 2>&1; \
grep "virtualdesktopbar" "$TMP_FILE" > "$FILE"; \
latte-dock --replace & disown
```

Once Latte Dock and the plasmoid is loaded, and once the issue occurs, press Ctrl+C in Konsole.

Then, please attach the content of the `virtualdesktopbar-debug.txt` file created in your home directory.

**Comment by master-of-zen** [comment]
[virtualdesktopbar-debug.txt](https://github.com/wsdfhjxc/virtual-desktop-bar/files/5609706/virtualdesktopbar-debug.txt)
@wsdfhjxc It loads straight to bug state, disabled composing looks like this 
![2020_11_28_00_20_35](https://user-images.githubusercontent.com/46526140/100487091-96405100-310f-11eb-9283-0f026c51c7c3.png)

**Comment by wsdfhjxc** [comment]
Thank you very much for the report. Unfortunately (or fortunately), I can't see any unusual QML errors in the log.

Could you please show me your Latte Dock configuration? Screenshots of the Behavior and Appearance tabs should be enough.

**Comment by master-of-zen** [comment]
Here is it @wsdfhjxc 
<details>
  <summary>Screenshots</summary>

![2020_11_28_23_43_30](https://user-images.githubusercontent.com/46526140/100526659-b76a7580-31d3-11eb-929d-0cdaf31719ce.jpg)

![2020_11_28_23_43_42](https://user-images.githubusercontent.com/46526140/100526660-b89ba280-31d3-11eb-8ba4-0905479ce050.jpg)


</details>

**Comment by master-of-zen** [comment]
Here they are @wsdfhjxc 
<details>
  <summary>Screenshots</summary>
 
![2020_11_28_23_46_21](https://user-images.githubusercontent.com/46526140/100526703-20ea8400-31d4-11eb-8460-e4319eab19c8.jpg)

![2020_11_28_23_46_13](https://user-images.githubusercontent.com/46526140/100526704-21831a80-31d4-11eb-8aa3-010f6afd51ef.jpg)

</details>

**Comment by wsdfhjxc** [comment]
I've made some changes. Can you please check out the `testing` branch, rebuild and reinstall the applet?

**Comment by master-of-zen** [comment]
@wsdfhjxc it fixes the issue, thank you :medal_sports: 
![2020_11_29_11_43_47](https://user-images.githubusercontent.com/46526140/100538400-3e513980-3238-11eb-953c-3d40ffeefc74.jpg)
