### ISSUE TITLE
Dynamic desktops are not assigned numbers

### ISSUE THREAD

**Issue by al2me6** [wsdfhjxc/virtual-desktop-bar#47]
After the latest updates, dynamic desktops are no longer numbered automatically. Instead, they are all named "New Desktop," rendering them impossible to distinguish in the desktop switcher menu.

It would appear that this behavior is hard-coded here: 

https://github.com/wsdfhjxc/virtual-desktop-bar/blob/51b490ae8252db748d1b7a970bd9e4e7c5544530/plugin/VirtualDesktopBar.cpp#L57-L58

**Comment by wsdfhjxc** [comment]
The fix is now available in the `master` branch.
