### ISSUE TITLE
Dynamic Desktop Doesn't Detect Spotify...

### ISSUE THREAD

**Issue by Prayag2** [wsdfhjxc/virtual-desktop-bar#48]
This is almost perfect but it doesn't detect spotify as an app in KDE Plasma. I am using Kubuntu 20.04. Here's a screenshot- 
![Screenshot_20201216_151937](https://user-images.githubusercontent.com/39525869/102332464-1f7dd180-3fb2-11eb-92a9-b65adbba34ac.png)
It isn't creating a new virtual desktop after opening Spotify. All other apps work just fine.

**Comment by wsdfhjxc** [comment]
The fix is now available in the `master` branch.
