### ISSUE TITLE
Error Loading Applet.qml , debian 10 kde plasma

### ISSUE THREAD

**Issue by cokeito** [wsdfhjxc/virtual-desktop-bar#53]
Error loading QML file: file:///usr/local/share/plasma/plasmoids/org.kde.plasma.virtualdesktopbar/contents/ui/applet/Applet.qml:7:1: module "org.kde.plasma.virtualdesktopbar" is not installed

hello, ive tried all the solutions around the similar errors on here with no success, any help?

cheers
J.

**Comment by cokeito** [comment]
hello anybody here ? :)

**Comment by wsdfhjxc** [comment]
Yeah, it seems I can't get the CMake cross-distro build right...

But can you please try this:

1. Remove the `build` folder.
2. Run the following commands:

```
mkdir build && cd build
cmake -DKDE_INSTALL_QMLDIR=/usr/lib/x86_64-linux-gnu/qt5/qml ..
make && sudo make install
```
3. Restart the panel: `plasmashell --replace & disown` \
(or, if you are using Latte: `latte-dock --replace & disown`)

If it's still not working, then I can't help you. I'll try to provide binary packages in the future.

**Comment by cokeito** [comment]
it works!
Thanks!
